language: node_js
sudo: false
node_js:
- 8.11.3
install:
- npm install
script:
- npm run build
deploy:
  provider: heroku
  app: vscodefy
  on:
    repo: vscodefy/vscodefy-server
  api_key:
    secure: $HEROKU_API_KEY
