language: node_js
sudo: false
node_js:
- 8.11.3
install:
- npm install
script:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: ytutCPqOE1uHbpnTlslHjyOYpEarD9u3Iz04K2QHRr7/ywG6EYNw6Adr3c06rstDo3Bkmyd1aun/Fhq+Lrbt6SB7+EopC35vYeYHJoA9Tkc0t2FWYoOKlb9uXB0hBpJz4RJ26wDPuWzlqJlrg/v/CAF0vAKQsH7p6v+0ettvwv9tdWP5l+cE6ATgu8dSLeA72sz7wDuTzZDCvpV5DuKOw4+pfufPuIBnA5P0wua49tBsw3u3BjdEDgtdWGSCE/oiDqppaetl8wIKSztWWeq2dz6XRYV5U1bGt79QL4SDFNU6W6ncaGpkkBLwDSwcOx+H7m0IyoRUHGS4CF2rkGxazGkCmL2t1QoWIIygPraqvP8k/1i2oLnVgQicvYMLa8VAKJEgZLokE71DvAAdu8ilWQwBGfO7+xUN+mIBuGb0NS04xPw2B1C4YJDFx7gYYH4NMQPKTn2wF7Vko04mYI8GcBhBIt8YjwfWntUE654gx792S8mK4O/xWjd188GtrBkv+X8yFiwgJJd1mrgDD8quj8XzvUAlkA/o0aepwvkNxuAHz57KCukVPZZf8h+CYLqgBUsKamSBp2l4gDEpFlU6m2CZ3HtE6gEwJ+CwvjqdGTYh+4U6YldIhL2YaQCSqJvkrDoYYYhrwqXDs4dF+1ypjT2rbPkkplQjBry6P133VBE=
  app: vscodefy-server
  on:
    repo: iagolaguna/vscodefy-server
