language: node_js
sudo: false
node_js:
- 8.11.3
install:
- npm install
script:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: XdcnRLmnFGc0ep3SInqSXa+Ps6bMCGdDo7H9awjSTyqgki60J/ORdUHPqAT87FJQnsIbOkMZsVzkOpMQtxsJYoie0pf6PXkmUjkHd8LTq3pQ1sda21AvfY4yWtVGVm7VDu21fzbgymWJm+qAHOHxu8gDdfGtecld9c7jJUku3yqXAbctI8ztIhy2X30bUUQJsUEP+DvTfiSgC6qa9izm0mrtpG+3/iqZhhNkaYDh1InhYBeRcCBOQbAfzmQnDD5e1MuTIevUj/JlWyNoAn/uNrkZ13d5uRasMJjRk3k83dG0U7yT2qGOr8yuCEPzVDmY6Gj1opCTdFBv2n6Djb28U0mHNE1Z+a+ONbuVVGvJQ04HN9U3eV9u9/c0N+XbxxRCBkRK8Yh0zEWUY9cw7QI64oGLYzcQE/Epqm18x/RnJaxzb6MYE8LTicZc63ggJVPwkK1njTiSl2hi43jh94ocvedzZ6OXXtSyBIbUlx9rV9JIUprEampLAzyRg1Zgn8N5/qs58eHlkyCWVY+/d/z4PxgRc8s1t9cfz8WqtKeTrQHgFv5fYyTbasYjk6H/Tls41blQnt6zV0NbOiWdJLercfKDBcQ0Wtn9tl4pL/XC8M+tfk5ELr/SB4eTUimDEu6eYhaX+WtzdzK/LIYabZjRWO6b11UjV1TlUrLR2Tk0HW4=
  app: vscodefy-server
  on:
    repo: iagolaguna/vscodefy-server
