language: node_js
sudo: false
node_js:
- 8.11.3
install:
- npm install
script:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: hemI3tYrfyZktuH+/30vNPXqK9XdjAdG52jdyAxwsU5lcJJl70iMN8SCB2lrR+lHGBtlZOZOXf5u6CE9g1Li6RQ84KaPtyDVmN/3wZXVcyKz7NVuVRkStldTFBRJ3XMn/Yckn11cZrunmJEKZrqdgg1O0aWD8xb8/m+1o70w2TtZ4sYHrbaFVUkea5hs0jENr6ujHu+/IMD7gCTYAHVOqHJ0bJ5Qa9VkenJD4TLk9KMSYcqC5GqzomndkSOGPK4STAekhR04prXZU4n6gag92dcySRViRx3+myXK5yUzRYPFa7Z8fLLyQYQvch7BDCdTrrlfQEiO2kAw7flhGXiWLk68rmokKrsdnDXyKsmwCOG8KV0KZ4+RMn85ebmkFBfYVYHCUkKnJNMKocSBe/YMeBqt7Y9x6EzPHnlU8AOpd2KCcKX8ik7U6VrD1ldsvGXUzo25ctGckpiDQav7u6snT4kBVqmH0mByv6gGtWHaOUk9wSEYPQAoAF+IeMNKeJnHMXUewR5gZPzQB18EzjWMS1vL9BMm7MTEPRwjiAT7DxRaTEqkvHWoYbBkDtv7TMOOCsTcKZdCBBdMPmtXdBddYiz95pME/syv6AMq5Pk1Or93sIyyVpmSJq27IB6hQXKTU7n2hRfa4CUjpgi00A6sgcGNUY+OJGbNYOKUhP3FH8E=
