language: node_js
sudo: false
node_js:
- 8.11.3
install:
- npm install
script:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: s2f+TMh+sxyaKRzKXp+3qaTIK7mFx5iKINBBHLSXtNW630RkDXL3x3PmXghqdpSYLyC3QiyOLteZb4bYn8ZCmpGzcZNtIvBLCzC4nKbnjDBD0IhFS9132dHRRlK1zROQnZMl2C1xdaxF/+keKp0GZZUSj4LZAYdwpYxDhipRVsu4x46W2w/jpRUh80x9WJj/WCVmJiDgKNjawiK6l9IEbcEb0GUn2+V81mOpZ4Y4qcLz6r9gVgzzQrv79GSCr/8gofRiMONX2tNfjQC73B/Tew+zI7sSygdldRN5cNIhEaoq4uiiIgFDn3WpmcYDD5IIAQdXe3NtorlNy9xpCsTCawMGrFxNYnqaWNalfa/uczHgVux+ImmZkOB1Si6xppemjHD+kahZJGEfv+6ZuO5zvF/ybzxsvjrgxmtRTKv/jtOJ0xamSku1pjMBb3FNoXrT6T3m8YLFQ0oWqF3VgpjeIyrLBdxatQjAuHAlab90lszAHAHnPB84h8E8qufofTaLFwckBXs68kUiI5TGu9j6j+a1uyEgMUa0Tj8k8FRWZeuwnW/C3l9Y+PY+wiGcmOdzKqB8Kezq8Fcn/mXOCrCNd8K/FnXXTgZjaCR1Zshrhw/16IreURa/oSHRmWoDrMnr9w7CRZ9uxWs/vuPrm3cLPENMra/SVEBgMUbPdZ6QIfo=
  app: vscodefy-server
  on:
    repo: iagolaguna/vscodefy-server
