language: node_js
sudo: false
node_js:
- 8.11.3
install:
- npm install
script:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: rthWdTB+KmQqtreFu4njdyd7tadEwz1rd+uNF4Yioi1P6DxPhHuwErHP7i32Vxdq9o3i0Tz1lHwl3QuLpPmlVY/2L5qMYkhJ9sFQmxcL25h+bTd2ntSwnZhgUEN41ZBJ+QV3llt26wAg2B62yP5W44CTyBEwqYQRgsmUjJIV9M4s/ljJ8toLiEs3JUr6+0bDSq+ejozkIi9VRgOLT1VuNqUedYQNV25r9uX4rNim5/28O+LguhOMP4hPDUq76iXumBFyboJoDp0yvxQY6BYQNc/zoYxE45lXXuqKYr9lhYNU5Fzsoobl/unWKt5i8CHoT2EXi6U6q4fyRcIb28mwn9zP26ZWckgQlrGpocb6vmHMA7SUT3qDm6CA9onbR7sqVWAWxTB3TjzMruSnpQbQYSZ2csiAZS5qtsmeWBkEPn2h00/HO3M0nePaYwR8P+c4NPzllF2KFuin5//M2AfvnGlPDoSQAIrtSsBwHcmU8vIAxB/UEwfGFLxaROoaVoiLBgQautA/iXgbauzFnnj8r+UvnhZRh+41vb9Y8HgsMRJUUE5GoUtKo+CjaQvA8dcYKtd0DeUT1cRNlJLeOyxT5L9Dh2OcgK4SileROQpVfTdRwp+N4Ah0AuYivd6wxHm85YP1V5bFN+jMMQUBxaOxyfr8RLVBuzxl29uif5NELBw=
  app: vscodefy-server
  on:
    repo: iagolaguna/vscodefy-server
