language: node_js
sudo: false
node_js:
- 8.11.3
install:
- npm install
script:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: FeQ6tE6vocuLyBppbM0cKIUGaUDwvlxN+WWamdkbzRtWmQwOGJ+JtxS3R5Gn+r+QnP/TaILBUPxDki/LiCVOIR39pIgnpobHFyJuX0zfm6oGfZ1/ser3qn1j8mJcLq5NLr2V8PfvI0mODl9pv9vhaknlRfB45wf2XO1cXvCsOVrrvuOVwcoVut/7XIMYKp4l76ljbGgEZnYxhd/1vewlX8zCbX4lx27DaSkjvNUp8lyqVF/uI4pW8A55m8k6CmKnPCQ7x5kqYY39Hv0Xd+fw2zkyiE5cNh4sufv7y7lIGbH4vrTZ3yfmUFRPXfEqmJjtWKV8eRdthZ5NssG4fC+1zpXGmaGSkwL0cKqhi9gGr6EIQpgdSbTJI9pEu8QBXveGn5ZlWk01HWAyCxbqwQFwza52YQVQY6R7BR2wtAV5bPtKVS8QP4YVopZ/8Uk3Io+Xntab6sfc7v8WzlKx3Q8RaBzPtM6fuvWeeelFvgpBn/pLRyBCfHXQjTsN/TACX42QAHCV2skSc2F1mMkPKF3a331yY27gzbfzRVzdS3aY+dLGN261JbNYlJ+JhPLXWIzWMEntPfsKE8FfVrSbipIvQcT0xZ/imnGka0gIC49zGBjxEQyTZBbu/tS4ZA2iRH3r/KYQ59MVriwMhYq0XFCoeHJhIkS2nrA3eWKlggISgTI=
