language: node_js
sudo: false
node_js:
- 8.11.3
install:
- npm install
script:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: pBiGFWpLR9Lw5YDp3L2deiOtDQHDDZOtPubpnm0m6CIlLmBtoD2xXDyGusapqxNNCTOg53HHrkCairZDx3G3PMYGIeS9D0ONggdCbwxpXIGb8XydqqiPISJvEIo17TjFZ0Sy/e33Yq+5LXd0lk9LRsb2ZpHlWwDD+yDT8DyPQmej/b67kMLZzw8j1kzj3xkYGjaWawUSxdt9nvXLx8mTAyFtHXGRBZZVAMzJegmJJDkufSt/QYtROAKq2zIYrivfiw6gJZEOTY2+mMPknycFRsH449Y2t8CL3CkG0wsm9KuAo6PpljvKMWCnSOgx4pWt4rLPf/gdwJo9ywWBqpQ2A32BUA+uPJIqt8mw+S2Ckk3JbLt4QjHKXM8eR4m2vE3mn0HHR5uMP3p9yPWl3rtV/JHQvOZWVmY9HBa7a2vbgJLZSTJLRE20Pu3TvDaMfxTLDZMpdqQNnTcIulwuxGphdgOpYZCkV+7Y5xwkyhTntKURK9pIaaNX2Ro/tnMMWxXDxELzLGOMcioWzbLyxZ78q5Y+AUk9H7y23zdRkiXMudg/WeO5B82/TSmPFitdhot8Yie9h4bMQL5tVOibU3RRQ8CPAunV6VHi/2kA97N4fLbJkTExAnrLSLPCib8aynhn9gqES4/yghDY7lZLwCyO+fHS0uXCRYlzdFfHA2yxeo8=
  app: vscodefy-server
  on:
    repo: iagolaguna/vscodefy-server
